name: Fetch Latest Spot-Hinta.fi Prices

on:
  # Ajetaan automaattisesti joka 15. minuutti
  schedule:
    - cron: '*/15 * * * *'
  # Lisätään nappi, jolla ajon voi käynnistää manuaalisesti
  workflow_dispatch:

# Annetaan työnkululle lupa tehdä "git push" eli kirjoittaa repositorioon.
permissions:
  contents: write

jobs:
  fetch-file:
    runs-on: ubuntu-latest
    steps:
      # Vaihe 1: Otetaan tämän repositorion tiedostot käyttöön
      - name: Check out repository
        uses: actions/checkout@v4

      # Vaihe 2: Ladataan data (UUDELLEENYRITYKSELLÄ)
      - name: Fetch spot-hinta.json (with retry)
        uses: nick-invision/retry@v2
        with:
          # Yritetään enintään 3 kertaa
          max_attempts: 3
          # Odotetaan 15 sekuntia yritysten välillä
          retry_wait_seconds: 15
          # Komento, jota yritetään ajaa
          command: |
            # --fail varmistaa, että curl epäonnistuu, jos API palauttaa virheen
            curl --fail "https://api.spot-hinta.fi/TodayAndDayForward" -o spot-hinta.json

      # Vaihe 3: Tallennetaan ("commit") tiedosto takaisin repositorioon
      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Lisätään tiedosto "stage"-tilaan
          git add spot-hinta.json

          # Tarkistetaan, onko muutoksia. Jos ei, lopetetaan tähän.
          if git diff --staged --quiet; then
            echo "No changes detected, exiting."
            exit 0
          fi
          
          # Jos muutoksia oli, tehdään commit
          git commit -m "Update spot-hinta.json"

          # Haetaan uusimmat muutokset GitHubista (rebase)
          # Tämä estää "(fetch first)" -virheen.
          git pull --rebase
          
          # Työnnetään muutokset takaisin repositorioon
          git push
