name: Fetch Latest Spot-Hinta.fi Prices

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-file:
    runs-on: ubuntu-latest
    steps:
      # Vaihe 1: Otetaan tämän repositorion tiedostot käyttöön
      - name: Check out repository
        uses: actions/checkout@v4

      # Vaihe 2: Ladataan data (UUDELLEENYRITYKSELLÄ)
      - name: Fetch spot-hinta.json (with retry)
        uses: nick-invision/retry@v2
        with:
          # LISÄTTY TÄMÄ:
          # Annetaan yhdelle yritykselle aikaa 60 sekuntia
          timeout_seconds: 60
          
          # Yritetään enintään 3 kertaa
          max_attempts: 3
          # Odotetaan 15 sekuntia yritysten välillä
          retry_wait_seconds: 15
          # Komento, jota yritetään ajaa
          command: |
            curl --fail "https://api.spot-hinta.fi/TodayAndDayForward" -o spot-hinta.json

      # Vaihe 3: Tallennetaan ("commit") tiedosto takaisin repositorioon
      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          git add spot-hinta.json

          if git diff --staged --quiet; then
            echo "No changes detected, exiting."
            exit 0
          fi
          
          git commit -m "Update spot-hinta.json"
          git pull --rebase
          git push
