name: Fetch Latest Spot-Hinta.fi Prices
on:
  schedule:
    # Run every 15 minutes between 11:00–12:59 UTC
    # This covers 14:00–15:59 Helsinki time year-round (EET/EEST)
    - cron: '0,15,30,45 11-12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-file:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Shallow checkout
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Step 2: Exit early if not 14:00 Helsinki local time
      - name: Ensure Helsinki local time is 14:00
        run: |
          HOUR=$(TZ="Europe/Helsinki" date +%H)
          echo "Current Helsinki hour: $HOUR"
          if [ "$HOUR" -ne 14 ]; then
            echo "⏭ Not 14:00 Helsinki time, exiting."
            exit 0
          fi

      # Step 3: Fetch data with retry
      - name: Fetch spot-hinta.json (with retry)
        uses: nick-invision/retry@v3
        with:
          timeout_seconds: 30
          max_attempts: 2
          retry_wait_seconds: 10
          command: |
            curl --fail --connect-timeout 10 --max-time 25 \
              "https://api.spot-hinta.fi/TodayAndDayForward" -o spot-hinta.json

      # Step 4: Validate JSON
      - name: Validate JSON
        run: |
          if ! jq empty spot-hinta.json; then
            echo "❌ Invalid JSON received"
            exit 1
          fi

      # Step 5: Check if tomorrow's prices are available
      - name: Check if tomorrow's prices are available
        id: check_prices
        run: |
          PRICE_COUNT=$(jq '. | length' spot-hinta.json)
          echo "Found $PRICE_COUNT price entries"
          if [ "$PRICE_COUNT" -gt 96 ]; then
            echo "has_new_prices=true" >> $GITHUB_OUTPUT
            echo "✅ Tomorrow's prices are available!"
          else
            echo "has_new_prices=false" >> $GITHUB_OUTPUT
            echo "⏳ Still waiting for tomorrow's prices..."
          fi

      # Step 6: Commit and push if changed
      - name: Commit and push if changed
        if: steps.check_prices.outputs.has_new_prices == 'true'
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"

          git add spot-hinta.json
          if git diff --staged --quiet; then
            echo "No changes detected, skipping commit."
            exit 0
          fi

          DATE=$(date -d 'tomorrow' +%Y-%m-%d)
          git commit -m "Update spot-hinta.json with prices for $DATE [skip ci]"
          git push || (git pull --rebase && git push)

          echo "✅ Successfully updated with new prices!"
